version: "3.8"
services:
  ml_api:
    image: parmarav/calihousing-api:latest   
    container_name: ml_api
    environment:
      - MLFLOW_TRACKING_URI=http://host.docker.internal:5000  # adjust if using mlflow server
      - MODEL_NAME=CaliforniaHousingRegressor
      - MODEL_STAGE=Production
    ports:
      - "8000:8000"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

volumes:
  grafana-storage:

networks:
  monitoring:
