FROM python:3.9-slim

# install mlflow at build time
RUN pip install --no-cache-dir mlflow

WORKDIR /app

# create the directories so volumes map correctly
RUN mkdir /mlruns && touch /mlflow.db

EXPOSE 5000

CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "/mlruns", "--host", "0.0.0.0", "--port", "5000"]
